[package]
name = "campaignbotrs"
version = "0.1.0"
authors = ["sahay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.7.2"
rand = "0.7.0"
nom = "5.0"
sqlite3 = "0.24.0"